version: "3"
services:
      web:
        container_name: nginxServer.13
        build:
          context: ./docker
          dockerfile: web.dockerfile
        volumes:
          - "./:/var/www"
          - "./html:/usr/share/nginx/html"
          - "./docker/vhost.conf:/etc/nginx/conf.d/default.conf"
        ports:
          - "9000:80"
        links:
          - app
      app:
        container_name: php7.2fpm
        build:
          context: ./docker
          dockerfile: app.dockerfile
        volumes:
          - ".:/var/www:rw"
          - "./html:/var/www/html"
        expose:
          - "9000" 
          